#!/bin/bash

# Matt Hansen (mah60@psu.edu) - 3/3/2014
# modified for DEP by rzm102 - 01/25/2016
# Added code for automatic group - 01/29/2018
# Added code for json by atlauren - 06/01/2022
#    https://bigfix.slack.com/archives/CA4N683J6/p1652397740502799

/usr/sbin/chown root:wheel "${3}/Library/LaunchDaemons/BESAgentDaemon.plist"

/usr/sbin/chown -f -R root:wheel "${3}/Library/BESAgent"

/bin/chmod -f -R go-wx "${3}/Library/BESAgent"
/bin/chmod -f -R go+X "${3}/Library/BESAgent"

if [[ ! -e "${3}/Library/Application Support/BigFix/BES Agent/" ]]; then
	mkdir -p "${3}/Library/Application Support/BigFix/BES Agent/"
fi
/usr/sbin/chown -f -R root:wheel "${3}/Library/Application Support/BigFix/BES Agent"

if [[ ! -f "${3}/Library/Preferences/com.bigfix.BESAgent.plist" ]]; then
	if [[ -f "clientsettings.cfg" ]]; then
		echo "No com.bigfix.BESAgent.plist on the host, found clientsettings.cfg"
		"${3}/Library/BESAgent/BESAgent.app/Contents/MacOS/CfgToPList.pl" "clientsettings.cfg" "$INSTALLER_TEMP/clientsettings.json"
	fi
	if [[ -f "$INSTALLER_TEMP/clientsettings.json" ]]; then
		echo "Applying custom settings"
			/Library/BESAgent/BESAgent.app/Contents/MacOS/BESAgent -setSettings "$INSTALLER_TEMP/clientsettings.json"
	fi
fi

if [[ -f "brand.txt" ]]; then
	echo "Found brand.txt, checking for com.bigfix.BESAgent.plist"
	if [[ -f "${3}/Library/Preferences/com.bigfix.BESAgent.plist" ]]; then
		BESBRAND=$(cat "brand.txt")
		echo "Found com.bigfix.BESAgent.plist, adding brand: $BESBRAND"
		defaults write "${3}/Library/Preferences/com.bigfix.BESAgent.plist" Brand -string "$BESBRAND"
	else
		echo "Could not find com.bigfix.BESAgent.plist"
	fi
fi

if [[ -f "actionsite.afxm" ]]; then
	echo "Found actionsite.afxm, installing it..."
	cp "actionsite.afxm" "${3}/Library/Application Support/BigFix/BES Agent/"
fi

if [ "${3}" == "/" ]; then
	echo "Target is internal drive, starting daemon..."
	launchctl load /Library/LaunchDaemons/BESAgentDaemon.plist
fi

exit 0
